// Generated by scripts/generate_vocab_audio.py — do not edit by hand.
// Vocabulary recordings for Learning materials, keyed by speakText.

import belajar from "@/assets/audio/vocab/belajar.mp3";
import besarkanSuara from "@/assets/audio/vocab/besarkan-suara.mp3";
import hadir from "@/assets/audio/vocab/hadir.mp3";
import ingat from "@/assets/audio/vocab/ingat.mp3";
import kecilkanSuara from "@/assets/audio/vocab/kecilkan-suara.mp3";
import kemarin from "@/assets/audio/vocab/kemarin.mp3";
import masukkan from "@/assets/audio/vocab/masukkan.mp3";
import matikan from "@/assets/audio/vocab/matikan.mp3";
import mengabsen from "@/assets/audio/vocab/mengabsen.mp3";
import mengulas from "@/assets/audio/vocab/mengulas.mp3";
import nyalakan from "@/assets/audio/vocab/nyalakan.mp3";
import papanTulisElektronik from "@/assets/audio/vocab/papan-tulis-elektronik.mp3";
import pelajaran from "@/assets/audio/vocab/pelajaran.mp3";
import pelajaranDimulai from "@/assets/audio/vocab/pelajaran-dimulai.mp3";
import siap from "@/assets/audio/vocab/siap.mp3";
import speaker from "@/assets/audio/vocab/speaker.mp3";
import steker from "@/assets/audio/vocab/steker.mp3";
import stopkontak from "@/assets/audio/vocab/stopkontak.mp3";
import suara from "@/assets/audio/vocab/suara.mp3";
import tekan from "@/assets/audio/vocab/tekan.mp3";
import tombol from "@/assets/audio/vocab/tombol.mp3";
import waktunyaBelajar from "@/assets/audio/vocab/waktunya-belajar.mp3";

export const vocabAudio: Record<string, number> = {
  "belajar": belajar,
  "besarkan suara": besarkanSuara,
  "hadir": hadir,
  "ingat": ingat,
  "kecilkan suara": kecilkanSuara,
  "kemarin": kemarin,
  "masukkan": masukkan,
  "matikan": matikan,
  "mengabsen": mengabsen,
  "mengulas": mengulas,
  "nyalakan": nyalakan,
  "papan tulis elektronik": papanTulisElektronik,
  "pelajaran": pelajaran,
  "pelajaran dimulai": pelajaranDimulai,
  "siap": siap,
  "speaker": speaker,
  "steker": steker,
  "stopkontak": stopkontak,
  "suara": suara,
  "tekan": tekan,
  "tombol": tombol,
  "waktunya belajar": waktunyaBelajar,
};
