"""Record the narrator voiceover for the app intro video (run once per script change).

Writes public/voiceover/<scene>.mp3 and src/voiceover.ts (scene durations in
seconds), so each scene lasts as long as its line.

Usage (from marketing-video/, OPENAI_API_KEY in ../vision-agent/.env):
    ../vision-agent/.venv/Scripts/python.exe scripts/generate_voiceover.py
"""

import json
import subprocess
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "public" / "voiceover"
INDEX_FILE = ROOT / "src" / "voiceover.ts"

MODEL = "gpt-4o-mini-tts"
VOICE = "marin"
INSTRUCTIONS = (
    "You are a warm, friendly narrator for a short app introduction aimed at parents, "
    "teachers and schools. Sound clear, upbeat and trustworthy, at a relaxed but lively "
    "pace. Pronounce 'Bu Guru' the Indonesian way: boo GOO-roo."
)

# Scene id -> narration. Keep ids in sync with the scenes in src/IntroVideo.tsx.
SCRIPT = [
    ("intro", "Meet Lingua: a friendly AI teacher that helps children learn Indonesian."),
    ("topics", "It's built around eighteen illustrated classroom comics, made for primary schools in Taiwan."),
    ("materials", "Children explore picture lessons, and hear every word in a clear, natural voice."),
    ("practice", "In Practice, they listen, repeat, and answer, one step at a time."),
    ("roleplay", "In Role Play, they talk live with Bu Guru, who gently corrects mistakes right away."),
    ("review", "Every session ends with stars, praise, and simple tips to improve."),
    ("progress", "Daily goals and a clear path through every topic keep learning on track."),
    ("trust", "It works in English or Traditional Chinese, and asks only for a nickname and grade."),
    ("outro", "Lingua. Speak Indonesian with confidence."),
]


def duration_seconds(path: Path) -> float:
    out = subprocess.run(
        ["npx", "remotion", "ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(path)],
        cwd=ROOT, capture_output=True, text=True, shell=True, check=True,
    ).stdout
    return float(out.strip().splitlines()[-1])


def main() -> None:
    load_dotenv(ROOT.parent / "vision-agent" / ".env")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    client = OpenAI()
    durations = {}
    for scene_id, text in SCRIPT:
        path = OUT_DIR / f"{scene_id}.mp3"
        print(f"recording {scene_id}")
        audio = client.audio.speech.create(
            model=MODEL, voice=VOICE, input=text, instructions=INSTRUCTIONS, response_format="mp3"
        ).content
        path.write_bytes(audio)
        durations[scene_id] = round(duration_seconds(path), 2)

    lines = [
        "// Generated by scripts/generate_voiceover.py — do not edit by hand.",
        "export const VOICEOVER = " + json.dumps(
            [{"id": sid, "text": text, "seconds": durations[sid]} for sid, text in SCRIPT],
            indent=2,
        ) + " as const;",
        "",
        "export type SceneId = (typeof VOICEOVER)[number][\"id\"];",
        "",
    ]
    INDEX_FILE.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(json.dumps(durations, indent=1), "total", round(sum(durations.values()), 1))


if __name__ == "__main__":
    main()
