// Generated by scripts/generate_voiceover.py — do not edit by hand.
export const VOICEOVER_EN = [
  {
    "id": "intro",
    "text": "Meet Lingua: a friendly AI teacher that helps children learn Indonesian.",
    "seconds": 5.02
  },
  {
    "id": "topics",
    "text": "It's built around eighteen illustrated classroom comics, made for primary schools in Taiwan.",
    "seconds": 5.9
  },
  {
    "id": "materials",
    "text": "Children explore picture lessons, and hear every word in a clear, natural voice.",
    "seconds": 5.3
  },
  {
    "id": "practice",
    "text": "In Practice, they listen, repeat, and answer, one step at a time.",
    "seconds": 4.97
  },
  {
    "id": "roleplay",
    "text": "In Role Play, they talk live with Bu Guru, who gently corrects mistakes right away.",
    "seconds": 5.66
  },
  {
    "id": "review",
    "text": "Every session ends with stars, praise, and simple tips to improve.",
    "seconds": 4.92
  },
  {
    "id": "progress",
    "text": "Daily goals and a clear path through every topic keep learning on track.",
    "seconds": 5.02
  },
  {
    "id": "trust",
    "text": "It works in English or Traditional Chinese, and asks only for a nickname and grade.",
    "seconds": 6.17
  },
  {
    "id": "outro",
    "text": "Lingua. Speak Indonesian with confidence.",
    "seconds": 3.5
  }
] as const;
