// Generated by scripts/generate_voiceover.py — do not edit by hand.
export const VOICEOVER_ZH_TW = [
  {
    "id": "intro",
    "text": "認識 Lingua：一位親切的 AI 老師，陪孩子輕鬆學印尼語。",
    "seconds": 6.41
  },
  {
    "id": "topics",
    "text": "課程圍繞十八個課堂漫畫主題，專為台灣的國小設計。",
    "seconds": 6.17
  },
  {
    "id": "materials",
    "text": "孩子可以看圖學習，每個單字都有清楚、自然的發音。",
    "seconds": 6.5
  },
  {
    "id": "practice",
    "text": "在練習模式，孩子一步一步地聽、跟著說，再回答。",
    "seconds": 6.31
  },
  {
    "id": "roleplay",
    "text": "在角色扮演中，孩子和 Bu Guru 即時對話，說錯時，老師會溫柔地馬上糾正。",
    "seconds": 9.46
  },
  {
    "id": "review",
    "text": "每次練習結束，孩子會得到星星、鼓勵，和簡單的改進建議。",
    "seconds": 6.55
  },
  {
    "id": "progress",
    "text": "每日目標和清楚的學習路徑，讓孩子穩定進步。",
    "seconds": 5.81
  },
  {
    "id": "trust",
    "text": "App 可以用繁體中文或英文，而且只需要暱稱和年級。",
    "seconds": 7.51
  },
  {
    "id": "outro",
    "text": "Lingua，讓孩子自信說印尼語。",
    "seconds": 4.46
  }
] as const;
