"""Generate the Learning material vocabulary audio (run once, not in the app).

Reads every `speakText` from data/learningMaterials.ts, asks OpenAI TTS for a
natural Indonesian recording, saves it to assets/audio/vocab/<slug>.mp3 and
rewrites constants/audio.ts so the app can play the files offline.

Usage (from the repo root, OPENAI_API_KEY in vision-agent/.env):
    vision-agent/.venv/Scripts/python.exe scripts/generate_vocab_audio.py
Existing files are kept; pass --force to record them again.
"""

import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "vision-agent"))
from pronunciation import indonesian_syllables  # noqa: E402

DATA_FILE = ROOT / "data" / "learningMaterials.ts"
AUDIO_DIR = ROOT / "assets" / "audio" / "vocab"
INDEX_FILE = ROOT / "constants" / "audio.ts"

MODEL = "gpt-4o-mini-tts"
VOICE = "marin"  # same voice as Bu Guru in AI Teacher
MAX_TRIES = 4


def instructions(text: str) -> str:
    syllables = " ".join(indonesian_syllables(word) for word in text.split())
    return (
        "You are a friendly native Indonesian primary-school teacher. Say the Indonesian "
        "word or phrase exactly as written, once, in Bahasa Indonesia — never English or "
        "German. Syllables: " + syllables + ". Pure Indonesian vowels (a = ah, e = eh or a "
        "short schwa, i = ee, u = oo), every syllable clear. Speak a little slowly and "
        "warmly, for young children. Say nothing else."
    )


def normalize(text: str) -> str:
    return re.sub(r"[^a-z ]", "", text.lower()).strip()


def similarity(a: str, b: str) -> float:
    from difflib import SequenceMatcher

    return SequenceMatcher(None, normalize(a), normalize(b)).ratio()


def record(client: OpenAI, text: str, path: Path) -> None:
    """Record, check by transcribing it back, keep the closest of a few tries."""
    best_score, best_audio = -1.0, b""
    for attempt in range(1, MAX_TRIES + 1):
        audio = client.audio.speech.create(
            model=MODEL,
            voice=VOICE,
            input=text,
            instructions=instructions(text),
            response_format="mp3",
        ).content
        path.write_bytes(audio)
        with open(path, "rb") as f:
            heard = client.audio.transcriptions.create(
                model="gpt-4o-transcribe", file=f, language="id"
            ).text
        score = similarity(text, heard)
        print(f"  try {attempt}: heard {heard!r} ({score:.2f})")
        if score > best_score:
            best_score, best_audio = score, audio
        if normalize(heard) == normalize(text):
            break
    path.write_bytes(best_audio)
    if best_score < 1.0:
        print(f"  CHECK BY EAR: best match {best_score:.2f}")


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def camel(slug: str) -> str:
    head, *rest = slug.split("-")
    return head + "".join(part.capitalize() for part in rest)


def main() -> None:
    load_dotenv(ROOT / "vision-agent" / ".env")
    force = "--force" in sys.argv
    texts = sorted(set(re.findall(r'speakText:\s*"([^"]+)"', DATA_FILE.read_text(encoding="utf-8"))))
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    client = OpenAI()

    for text in texts:
        path = AUDIO_DIR / f"{slugify(text)}.mp3"
        if path.exists() and not force:
            continue
        print(f"recording: {text}")
        record(client, text, path)

    lines = [
        "// Generated by scripts/generate_vocab_audio.py — do not edit by hand.",
        "// Vocabulary recordings for Learning materials, keyed by speakText.",
        "",
    ]
    for text in texts:
        slug = slugify(text)
        lines.append(f'import {camel(slug)} from "@/assets/audio/vocab/{slug}.mp3";')
    lines += ["", "export const vocabAudio: Record<string, number> = {"]
    for text in texts:
        lines.append(f'  "{text}": {camel(slugify(text))},')
    lines += ["};", ""]
    INDEX_FILE.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"done: {len(texts)} words -> {INDEX_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
